clt/urls.py
from django.contrib import admin
from django.urls import path, include
# import settings and static to setup media file serving
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('monitoring/', include('monitoring.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

monitoring/urls.py
from django.urls import path
from . import views

app_name = "monitoring"
urlpatterns = [
    path('', views.index, name="index"),
    path('history', views.history, name="history"),
    path('login', views.login, name="login"),
    path('statistics', views.statistics, name="statistics"),
    path('profile', views.profile, name="profile"),
    path('reports', views.reports, name="reports"),
    path('wreset', views.wreset, name="wreset"),
    path('dreset', views.dreset, name="dreset")
]

monitoring/models.py
from django.db import models
from datetime import timedelta


class Officer(models.Model):
    student_number = models.CharField(primary_key=True, null=False, max_length=7)
    first_name = models.CharField(max_length=128)
    middle_initial = models.CharField(max_length=128)
    last_name = models.CharField(max_length=128)
    sex = models.CharField(max_length=1, choices=(('M', 'MALE'), ('F', 'FEMALE')))
    officer_type = models.CharField(max_length=5, choices=(('SSC', 'Supreme Student Council'), ('YLEAP', 'YLEAP')))
    cp_contact_number = models.CharField(max_length=11, null=True, blank=True)

    is_login = models.BooleanField(default=False, null=False)
    latest_login = models.DateTimeField(null=True, blank=True)
    latest_logout = models.DateTimeField(null=True, blank=True)
    weekly_time_spent = models.DurationField(null=False)
    daily_time_spent = models.DurationField(null=False)

    weekly_time_spent_hour = models.IntegerField(null=True, blank=True)
    weekly_time_spent_minutes = models.IntegerField(null=True, blank=True)
    daily_time_spent_hour = models.IntegerField(null=True, blank=True)
    daily_time_spent_minutes = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.last_name + ", " + self.first_name


class Login(models.Model):
    officer = models.ForeignKey(Officer, on_delete=models.CASCADE)
    time_login = models.DateTimeField(null=False)
    time_logout = models.DateTimeField(null=True)
    duration = models.DurationField(null=True)

    temp_stn = models.CharField(null=False, max_length=7, default="")

    def __str__(self):
        return str(self.time_login) + " " + str(self.officer)

monitoring/forms.py
from django import forms
from .models import *


class LoginForm(forms.ModelForm):
    class Meta:
        model = Login
        fields = ('temp_stn',)

monitoring/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from datetime import datetime, timezone
from .forms import *
import logging
from django.http import HttpResponse


# enable logging in this application
logger = logging.getLogger(__name__)


@login_required(login_url='admin:login')
def index(request):
    return render(request, 'monitoring/index.html')


@login_required(login_url='admin:login')
def login(request):
    officer_data = Officer.objects.order_by('-latest_login')

    if request.method == "POST":
        officer_obj = get_object_or_404(Officer, student_number=request.POST['temp_stn'])

        if officer_obj.is_login:
            login_obj = Login.objects.filter(officer=officer_obj).latest("time_login")
            time = datetime.now(timezone.utc)

            # compute login duration
            duration = time - login_obj.time_login

            # compute weekly time spent, add it to existing computation
            if officer_obj.weekly_time_spent is None:
                weekly_time_spent = duration
            else:
                weekly_time_spent = officer_obj.weekly_time_spent + duration

            if officer_obj.daily_time_spent is None:
                daily_time_spent = duration
            else:
                daily_time_spent = officer_obj.daily_time_spent + duration

            # compute display variables
            weekly_time_spent_hours = weekly_time_spent.total_seconds() // 3600
            weekly_time_spent_minutes = (weekly_time_spent.total_seconds() % 3600) // 60
            daily_time_spent_hours = daily_time_spent.total_seconds() // 3600
            daily_time_spent_minutes = (daily_time_spent.total_seconds() % 3600) // 60

            # save the final model
            Officer.objects.filter(student_number=request.POST['temp_stn']).update(
                weekly_time_spent=weekly_time_spent,
                daily_time_spent=daily_time_spent,
                latest_logout=time,
                is_login=False,
                weekly_time_spent_hour=weekly_time_spent_hours,
                weekly_time_spent_minutes=weekly_time_spent_minutes,
                daily_time_spent_hour=daily_time_spent_hours,
                daily_time_spent_minutes=daily_time_spent_minutes)

            # update officer object
            Login.objects.filter(time_login=officer_obj.latest_login).update(time_logout=time, duration=duration)

        else:
            form = LoginForm(request.POST)
            time = datetime.now()

            # create login event record
            login_event = form.save(commit=False)
            login_event.officer = officer_obj
            login_event.time_login = time
            login_event.temp_stn = request.POST['temp_stn']

            # save login event to database
            login_event.save()

            # update officer object
            Officer.objects.filter(student_number=request.POST['temp_stn']).update(is_login=True, latest_login=time,
                                                                                   latest_logout=None)

    form = LoginForm
    return render(request, 'monitoring/login.html', {'form': form, 'officer_data': officer_data})


@login_required(login_url='admin:login')
def dreset(request):

    if request.method == "GET":
        Officer.objects.all().update(daily_time_spent=None,
                                     daily_time_spent_hour=None,
                                     daily_time_spent_minutes=None,
                                     is_login=False)

        return HttpResponse(200)


@login_required(login_url='admin:login')
def wreset(request):

    if request.method == "GET":
        Officer.objects.all().update(weekly_time_spent=None,
                                     weekly_time_spent_hour=None,
                                     weekly_time_spent_minutes=None,
                                     is_login=False)

        return HttpResponse(200)


@login_required(login_url='admin:login')
def history(request):
    pass


@login_required(login_url='admin:login')
def statistics(request):
    pass


@login_required(login_url='admin:login')
def profile(request):
    pass


@login_required(login_url='admin:login')
def reports(request):
    pass

monitoring/templates/monitoring/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% endblock %}

monitoring/templates/monitoring/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div id="base-frm-container" class="col-md-2">

        <div id="frm-container" style="margin-left: 10px; margin-top: 30px;">
            <form method="POST" class="frm post-form">{% csrf_token %}
                {{ form.non_field_errors }}
                <div class="fieldWrapper form-input-text">
                    {{ form.temp_stn.errors }}
                    <label style="width: 140px;" class="form-label" for="{{ form.temp_stn.id_for_label }}">STUDENT NUMBER</label>
                    {{ form.temp_stn }}
                </div>

                <button type="submit" class="save btn btn-x"
                        style="font-size: 16px;
                            border-radius: 0;
                            border: none;
                            padding: 10px 40px 10px 40px;
                            color: white;
                            margin-top: 15px;
                            margin-left: 0;
                            background: #B24592;  /* fallback for old browsers */
                            background: -webkit-linear-gradient(to right, #F15F79, #B24592);  /* Chrome 10-25, Safari 5.1-6 */
                            background: linear-gradient(to right, #F15F79, #B24592); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
                ">CONFIRM
                </button>
            </form>
        </div>
    </div>

 <div id="base-table-container" class="col-md-10">
        <div class="row" id="table-content" style="width: 70vw; margin-left: 70px; margin-top: 20px;">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col" style="width: 24%;"></th>
                    <th scope="col" style="width: 18%;">LATEST LOGIN</th>
                    <th scope="col" style="width: 18%;">LATEST LOGOUT</th>
                    <th scope="col" style="width: 15%;">WEEKLY TIME SPENT</th>
                    <th scope="col" style="width: 15%;">DAILY TIME SPENT</th>
                </tr>
                </thead>
                <tbody>
                {% for each in officer_data %}
                    <tr>
                        <td>{{ each.last_name}}<span>, </span>{{each.first_name }}</td>
                        <td>{{ each.latest_login }}</td>
                        {% if each.latest_logout == None and each.latest_login != None %}
                        <td>Currently Login</td>
                        {% else %}
                        <td>{{ each.latest_logout }}</td>
                        {% endif %}
                        {% if each.weekly_time_spent == 0 %}
                        <td>No data</td>
                        {% else %}
                        <td>{{ each.weekly_time_spent_hour }}<span> hrs </span>{{ each.weekly_time_spent_minutes }}<span> mins</span></td>
                        {% endif %}
                        {% if each.daily_time_spent == 0 %}
                        <td>No data</td>
                        {% else %}
                        <td>{{ each.daily_time_spent_hour }}<span> hrs </span>{{ each.daily_time_spent_minutes }}<span> mins</span></td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
<style>
input#id_temp_stn {
    width: 200px;
    height: 40px;
    font-size: 28px;
    text-align: center;
}
</style>
{% endblock %}

monitoring/templates/monitoring/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% endblock %}

monitoring/templates/monitoring/statistics.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>SSC Monitoring System</title>

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
<div class="container-fluid">
    <div class="row" id="app-navbar">
        <div>
            <img src="{% static 'icon.png' %}"
                    style="height: 48px; padding-left: 15px; margin-top: -36px;"/>
        </div>
        <a class="remove-hover-underline" href="{% url 'monitoring:index' %}">
        <div id="app-navbar-title">
            <h3 class="app-navbar-text app-navbar-title">Monitoring System</h3>
            <h3 class="app-navbar-text app-navbar-subtitle">Supreme Student Council TIP-QC</h3>
        </div></a>

        <div class="nav-links">
            <a class="remove-hover-underline" href="{% url 'monitoring:statistics' %}"><h2>Statistics</h2></a>
            <a class="remove-hover-underline" href="{% url 'monitoring:profile' %}"><h2>Profile</h2></a>
            <a class="remove-hover-underline" href="{% url 'monitoring:reports' %}"><h2>Generate Report</h2></a>
        </div>
    </div>
</div>
<!-- content from templates will be inserted here -->
<div class="container-fluid">
    {% block content %}
    {% endblock content %}
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/jquery-3.3.1.js' %}"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/shards.js' %}"></script>
<script src="{% static 'js/base.js' %}"></script>
</body>
</html>